### PR TITLE
Report total allocations per-capability in eventlog-summary

### PR DESCRIPTION
**Pull request by mpardalos**
Example output:
```
...
---
Max threads: 395
Total allocations:
  * Capability 0: 1316MB
  * Capability 1: 1814MB
  * Capability 2: 1153MB
  * Capability 3: 1136MB
Max live: 276MB
It's fine
```
I wanted to add example output to the README but I'm not sure how to get an eventlog out of stack (since the example there currently is from stack). Marked as draft because of this. I could replace the example there with one from `ghcide` since that would be a bit easier for me to get.

### CODE REVIEW

**Comment by ethercrow** [comment]
> I could replace the example there with one from ghcide since that would be a bit easier for me to get.

Sure, I don't think it matters too much which exactly program was instrumented, feel free to replace.

**Comment by mpardalos** [comment]
Done. Should be ready to merge now.

**Comment by mpardalos** [comment]
Minor note: I had to hand-format the output. Was that originally the case or should I consider it a bug? The columns were completely misaligned in the terminal output.

**Comment by ethercrow** [comment]
> The columns were completely misaligned in the terminal output.

Terminal output only does a minimal effort to align things and breaks easily. This definitely can be improved.

**Pull request merged**
