### PR TITLE
Implement Zipkin exporter

### PR DESCRIPTION
**Pull request by ethercrow**

### CODE REVIEW

**Comment by ethercrow** [comment]
@mpickering does it make sense to try to do this through a named pipe?

**Comment by mpickering** [comment]
A named pipe seems like a sensible idea.

**Comment by mpickering** [comment]
@ethercrow When this is ready to try out I'm interested in giving it a test run.

**Comment by ethercrow** [comment]
@mpickering I think I just got it into some minimally usable state where you can run an instrumented program and export the eventlog into any zipkin-compatible services.

I think I'll merge this PR as is and document what's there and what's missing in the README and issues.

**Comment by ethercrow** [comment]
Oh, and the format of data I put in eventlog is very stringly and dumb.

**Comment by mpickering** [comment]
Is the format of the needed traces documented somewhere? If it is then I can make GHC emit traces in that format which would be a good showcase.

**Comment by ethercrow** [comment]
@mpickering One issue is that there are multiple such formats and the one that is supposed to replace them all is not final.

Another is that all these formats describe a span as an atomic thing. And here we are putting small pieces like "begin span ...", "set tag ..." and "end span" in the eventlog. To my knowledge no other library operates at this level and there's no documented format for it.

**Pull request merged**
